version: 2.1

jobs:
  prepare:
    working_directory: /tmp/project
    docker:
      - image: cimg/android:2024.01
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    working_directory: /tmp/project
    docker:
      - image: cimg/android:2024.01
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: ./gradlew test

  build-release:
    working_directory: /tmp/project
    docker:
      - image: cimg/android:2024.01
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Release
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/

workflows:
  version: 2
  test-and-build:
    jobs:
      - prepare:
          filters:
            branches:
              only: main
      - test:
          requires:
            - prepare
          filters:
            branches:
              only: main
      - build-release:
          requires:
            - test
          filters:
            branches:
              only: main