version: 2.1

jobs:
  prepare:
    working_directory: /tmp/project
    docker:
      - image: cimg/android:2024.01
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    working_directory: /tmp/project
    docker:
      - image: cimg/android:2024.01
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: ./gradlew test

  build-release:
    working_directory: /tmp/project
    docker:
      - image: cimg/android:2024.01
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Release
          command: ./gradlew build
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: release

workflows:
  version: 2
  test-and-build:
    jobs:
      - prepare:
          filters:
            branches:
              only: main
      - test:
          requires:
            - prepare
          filters:
            branches:
              only: main
      - build-release:
          requires:
            - test
          filters:
            branches:
              only: main